## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugo-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "https://therkildsen-lab.github.io/galapagos_website/"
publishDir = "public"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------


[Params]
  description = "The galapos sea cucumber project website"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  github = "https://github.com/"
  twitter = "https://twitter.com/"
  email = "NAME at DOMAIN dot com"
  instagram = "https://instagram.com/"
  linkedin = "https://linkedin.com/in/"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]
