## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "The Galapagos Project"
#theme = "hugo-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"

# Local
baseURL = "/"
publishDir = "public"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]

[Params.social]