## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

theme = "hugo-story"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "https://therkildsen-lab.github.io/galapagos_website/"
publishDir = "public"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "section"]

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]

[Params.social]