on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main
  workflow_dispatch:
    # to run manual builds

jobs:
  build_and_deploy_hugo_site:
    runs-on: ubuntu-latest
    name: Build and deploy Hugo site

    steps:
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true
    
    - name: Checkout repo on source_branch
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        # <<recommended if project uses git submodules for any purpose>>
        # <<required if deploying to git submodule directory>>
        fetch-depth: '0'
        # <<fetch-depth: '0' currently required until shallow clone problems are solved>>
        
    - name: Build site and push to release branch
      uses: aormsby/hugo-deploy-to-pages@v2.1
      id: build_step  # <<for outputs>>
      with:
        source_branch: 'main'
        release_branch: 'gh-pages'
        hugo_build_options: '-gc --minify'
        # submodule_release_branch: 'subbed' <<only provide if you are publishing to directory with git submodule>>
        # full_rebuild: true
        # hugo_publish_directory: 'documents'   <<publish to another directory if needed>>
        # commit_message: "I love this action."
        # test_mode: true <<enable to run a few verification tests before your first live run>>
